import {StyleSheet} from 'react-native';
export const voiceCallStyles = StyleSheet.create({
  mini:{backgroundColor:'#173b31',flexDirection:'row',paddingHorizontal:12,paddingBottom:8,alignItems:'center',gap:8},
  miniMain:{flex:1,flexDirection:'row',gap:12,alignItems:'center',minHeight:48},
  miniTitle:{color:'#edf8f1',fontSize:15,fontWeight:'600'}, miniHint:{color:'#acd0bd',fontSize:12,marginTop:2},
  miniEnd:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:'#4b292b'},
  headerButton:{width:48,height:48,alignItems:'center',justifyContent:'center'},
  timer:{color:'#c7d1cc',fontSize:16,fontVariant:['tabular-nums']},
  callTitle:{color:'#f4f0e8',fontSize:34,fontWeight:'600'},
  roomTitle:{color:'#a8b2ad',fontSize:16,marginTop:8,textAlign:'center'},
  controls:{flexDirection:'row',justifyContent:'center',gap:28},
  controlItem:{alignItems:'center',gap:10},
  controlButton:{width:64,height:64,borderRadius:32,backgroundColor:'#292d2c',alignItems:'center',justifyContent:'center'},
  controlLabel:{fontSize:13,color:'#c3ccc6'}, backgroundHint:{color:'#949e98',fontSize:12,textAlign:'center',marginTop:28},
  // 全画面表示（後ろのチャットは見せない）
  backdrop: { flex: 1, backgroundColor: '#0d0c10' },
  panel: { flex: 1, width: '100%', backgroundColor: '#0d0c10', paddingHorizontal: 24, paddingTop: 54, paddingBottom: 32 },
  header: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerText: { color: '#a49d92', fontSize: 13 },
  centerArea: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  orbArea: { paddingVertical: 30 },
  orb: {
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: '#bcd7fa',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cloud: { position: 'absolute', borderRadius: 999 },
  cloud1: { width: 154, height: 154, backgroundColor: '#e6f0ff', top: -25, left: -17 },
  cloud2: { width: 134, height: 134, backgroundColor: '#9fc2f5', bottom: -20, right: -14 },
  cloud3: { width: 112, height: 112, backgroundColor: '#cfe2ff', bottom: 25, left: 11 },
  gloss: { position: 'absolute', width: 98, height: 98, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.45)', top: 17, left: 28 },
  statusText: { color: '#a49d92', fontSize: 13, minHeight: 20, textAlign: 'center' },
  activityBox: { width: '100%', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#33313a', marginTop: 14, paddingTop: 10, gap: 4 },
  activityLine: { color: '#8f8a81', fontSize: 13, textAlign: 'center' },
  retryButton: { marginTop: 14, borderWidth: 1, borderColor: '#4a4650', borderRadius: 8, paddingHorizontal: 18, paddingVertical: 8 },
  retryText: { color: '#d9d2c8', fontSize: 14 },
});
