"""Dan two-note cues: G-D opening, D-G closing. Preview and firmware share PCM."""
import audioop
import argparse
import math
from pathlib import Path
import struct
import wave

RATE = 48000
G, D = 195.997718, 293.664768


def voice(t, frequency, decay, weight):
    if t < 0:
        return 0.
    # Felt-like rounded attack with a quiet, slower body behind it.
    attack = (1 - math.exp(-t / .018)) ** 2
    envelope = attack * (.79 * math.exp(-t / decay) + .21 * math.exp(-t / (decay * 1.65)))
    phase = 2 * math.pi * frequency * t
    body = (.34 * math.sin(phase)
            + .065 * math.sin(phase * 1.0018 + .23)
            + .045 * math.sin(phase * .9982 - .23)
            + .29 * math.sin(phase * 2)
            + .16 * math.sin(phase * 3)
            + .08 * math.exp(-t / .3) * math.sin(phase * 4)
            + .02 * math.exp(-t / .12) * math.sin(phase * 5))
    return weight * envelope * body


def render(standby=False):
    length = .88 if standby else .96
    notes = (D, G) if standby else (G, D)
    dry = []
    for i in range(round(length * RATE)):
        t = i / RATE
        weights = (.75, 1.0) if standby else (.92, .86)
        value = sum(voice(t - n * .13, f, .19 if standby else .235, weights[n])
                    for n, f in enumerate(notes))
        dry.append(value)
    # Diffuse, dark early reflections, designed in mono for the actual speaker.
    wet = [0.] * len(dry)
    for delay, gain in ((.029, .14), (.043, .11), (.067, .08), (.101, .055), (.139, .035)):
        shift = round(delay * RATE)
        damped = 0.
        alpha = 1 - math.exp(-2 * math.pi * 900 / RATE)
        for i in range(shift, len(dry)):
            damped += alpha * (dry[i - shift] - damped)
            wet[i] += gain * damped
    mixed = []
    for i, (body, tail) in enumerate(zip(dry, wet)):
        fade = min(1., (len(dry) - 1 - i) / (RATE * .18))
        fade = .5 - .5 * math.cos(math.pi * fade)
        mixed.append((body + tail) * fade)
    # Raise average loudness for the small speaker without hard clipping.
    # Soft peak compression preserves the rounded attack and two-note motif.
    rms = math.sqrt(sum(v*v for v in mixed) / len(mixed))
    gain = 10000 / rms
    pcm = [round(28500 * math.tanh(v * gain / 28500)) for v in mixed]
    assert pcm[0] == pcm[-1] == 0
    assert max(map(abs, pcm)) <= 28500
    return pcm


def write(path, pcm):
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), 'wb') as output:
        output.setnchannels(1); output.setsampwidth(2); output.setframerate(RATE)
        output.writeframes(struct.pack('<%dh' % len(pcm), *pcm))
    with wave.open(str(path), 'rb') as check:
        assert check.getnframes() == len(pcm)


def export_header(path, ready, standby):
    # Store 16 kHz PCM in flash, interpolate to the device's 48 kHz clock.
    # This preserves the layered sound without costly live synthesis.
    waiting = []
    for i in range(14400):
        t = i / RATE
        fade = .5-.5*math.cos(math.pi*min(1.,(14399-i)/4800))
        waiting.append(round(10000*voice(t,G,.09,1.)*fade))
    content = ['#pragma once', '#include <stdint.h>',
               '// Generated by preview_signature_cues.py --firmware-header; 16 kHz mono.']
    for label, pcm in (('ready', ready), ('standby', standby), ('waiting', waiting)):
        raw = struct.pack('<%dh' % len(pcm), *pcm)
        raw, _ = audioop.ratecv(raw,2,1,RATE,16000,None)
        values = struct.unpack('<%dh' % (len(raw)//2), raw)
        assert len(values)*3 % 240 == 0
        content.append('static const int16_t dan_cue_%s[] = {' % label)
        content.extend(','.join(map(str,values[i:i+24]))+',' for i in range(0,len(values),24))
        content.append('};')
    content += ['static const int16_t *dan_cue_data(int level){return level==1?dan_cue_ready:(level==2?dan_cue_standby:dan_cue_waiting);}',
                'static int dan_cue_samples(int level){return 3*(level==1?sizeof(dan_cue_ready)/2:(level==2?sizeof(dan_cue_standby)/2:sizeof(dan_cue_waiting)/2));}',
                'static int16_t dan_cue_sample(int level,int sample){',
                '    const int16_t *data=dan_cue_data(level);int index=sample/3,part=sample%3,count=dan_cue_samples(level)/3;',
                '    int a=data[index],b=index+1<count?data[index+1]:0;',
                '    return (int16_t)((a*(3-part)+b*part)/3);', '}']
    path.write_text('\n'.join(content)+'\n',encoding='utf-8')
    print('firmware PCM bytes',sum((len(x)//3)*2 for x in (ready,standby,waiting)))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    parser.add_argument('--firmware-header',type=Path)
    args = parser.parse_args()
    ready, standby = render(), render(True)
    if args.firmware_header:export_header(args.firmware_header,ready,standby)
    write(args.output, [0]*9600 + ready + [0]*48000 + standby + [0]*24000)
    for label, samples in (('ready', ready), ('standby', standby)):
        write(args.output.with_name('Dan-' + label + '-two-note.wav'), samples)
        print(label, 'peak', max(map(abs, samples)),
              'rms', round(math.sqrt(sum(v*v for v in samples) / len(samples))))
    print(args.output)
