"""成果物ごとのページ一覧を走査して sitemap 用レジストリ(TS)を生成する。

frontend/src/app/artifacts/<slug>/**/page.tsx を走査し、
frontend/src/lib/artifact-pages.generated.ts に {slug: [paths]} を書き出す。
独自ドメイン公開時の app/sitemap.ts がこれを参照する。

使い方: python scripts/generate_sitemap_registry.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "frontend" / "src" / "app" / "artifacts"
OUT = ROOT / "frontend" / "src" / "lib" / "artifact-pages.generated.ts"


def pages_for(slug_dir: Path) -> list[str]:
    paths: list[str] = []
    for page in slug_dir.rglob("page.tsx"):
        rel = page.parent.relative_to(slug_dir).as_posix()
        paths.append("/" if rel == "." else f"/{rel}")
    return sorted(set(paths))


def main() -> int:
    registry: dict[str, list[str]] = {}
    for d in sorted(ARTIFACTS.iterdir()):
        if not d.is_dir() or d.name.startswith("[") or d.name.startswith("_"):
            continue
        pages = pages_for(d)
        if pages:
            registry[d.name] = pages
    body = json.dumps(registry, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.\n"
        "// 成果物ごとの公開ページ一覧（独自ドメイン公開時の sitemap 生成に使用）。\n"
        "export const ARTIFACT_PAGES: Record<string, string[]> = "
        + body
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(registry)} artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
