"""成果物ごとのページ一覧を走査して sitemap 用レジストリ(TS)を生成する。

frontend/src/app/artifacts/<slug>/**/page.tsx を走査し、
frontend/src/lib/artifact-pages.generated.ts に {slug: [paths]} を書き出す。
独自ドメイン公開時の app/sitemap.ts がこれを参照する。

あわせて frontend/src/app/artifacts/<slug>/sitemap.ts を持つ成果物については、
frontend/src/lib/artifact-sitemaps.generated.ts に {slug: () => import(...)} を書き出す。
質問ページのように投稿のたびに増える動的ページは page.tsx の走査では拾えないので、
成果物が自前の sitemap.ts を持つ場合は app/sitemap.ts がそちらを優先して使う。

使い方: python scripts/generate_sitemap_registry.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "frontend" / "src" / "app" / "artifacts"
OUT = ROOT / "frontend" / "src" / "lib" / "artifact-pages.generated.ts"
OUT_SITEMAPS = ROOT / "frontend" / "src" / "lib" / "artifact-sitemaps.generated.ts"


def pages_for(slug_dir: Path) -> list[str]:
    paths: list[str] = []
    for page in slug_dir.rglob("page.tsx"):
        rel = page.parent.relative_to(slug_dir).as_posix()
        # 動的セグメント（/qa/[id] 等）は URL として成立しないので載せない。
        # そうしたページは成果物側の sitemap.ts が実 ID で列挙する。
        if "[" in rel:
            continue
        paths.append("/" if rel == "." else f"/{rel}")
    return sorted(set(paths))


def write_sitemap_loaders(slugs: list[str]) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.",
        "// 自前の sitemap.ts を持つ成果物の読み込み口。app/sitemap.ts が ARTIFACT_PAGES より優先して使う。",
        'import type { MetadataRoute } from "next";',
        "",
        "type SitemapModule = {",
        "  default: () => MetadataRoute.Sitemap | Promise<MetadataRoute.Sitemap>;",
        "};",
        "",
        "export const ARTIFACT_SITEMAPS: Record<string, () => Promise<SitemapModule>> = {",
    ]
    for slug in slugs:
        lines.append(f'  "{slug}": () => import("@/app/artifacts/{slug}/sitemap"),')
    lines.append("};")
    OUT_SITEMAPS.write_text(chr(10).join(lines) + chr(10), encoding="utf-8")


def main() -> int:
    registry: dict[str, list[str]] = {}
    with_sitemap: list[str] = []
    for d in sorted(ARTIFACTS.iterdir()):
        if not d.is_dir() or d.name.startswith("[") or d.name.startswith("_"):
            continue
        pages = pages_for(d)
        if pages:
            registry[d.name] = pages
        if (d / "sitemap.ts").is_file():
            with_sitemap.append(d.name)
    body = json.dumps(registry, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.\n"
        "// 成果物ごとの公開ページ一覧（独自ドメイン公開時の sitemap 生成に使用）。\n"
        "export const ARTIFACT_PAGES: Record<string, string[]> = "
        + body
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(registry)} artifacts)")
    write_sitemap_loaders(with_sitemap)
    print(f"wrote {OUT_SITEMAPS} ({len(with_sitemap)} artifacts with own sitemap)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
