"""接続済み独自ドメインの host条件付き next.config rewrite を自動生成する。

chat_artifact の custom_domain を走査し、各ドメインについて
  /        (host=domain) -> /artifacts/<slug>
  /:path+  (host=domain) -> /artifacts/<slug>/:path+
を frontend/src/lib/custom-domain-rewrites.generated.ts に書き出す。

これにより独自ドメインのサブパス(/business 等)が「クリーンURLのまま」
正しい成果物ページに振り向けられる（middleware直接rewriteはネスト静的ルートを
解決できないが、next.config の host rewrite は incoming URL に直接マッチして確実）。
ドメインごとの焼き込みは不要 — 接続したら本スクリプト再実行で自動反映される。

使い方: python scripts/generate_custom_domain_rewrites.py
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
load_dotenv(ROOT / ".env")

OUT = ROOT / "frontend" / "src" / "lib" / "custom-domain-rewrites.generated.ts"


async def collect() -> list[tuple[str, str]]:
    from app.services.chat_artifact_service import ChatArtifactService

    mapping = await ChatArtifactService().list_custom_domain_map()  # host -> slug
    return sorted((host, slug) for host, slug in mapping.items() if host and slug)


def to_rewrites(pairs: list[tuple[str, str]]) -> list[dict]:
    rules: list[dict] = []
    for host, slug in pairs:
        rules.append(
            {"source": "/", "has": [{"type": "host", "value": host}],
             "destination": f"/artifacts/{slug}"}
        )
        rules.append(
            {"source": "/:path+", "has": [{"type": "host", "value": host}],
             "destination": f"/artifacts/{slug}/:path+"}
        )
    return rules


def main() -> int:
    pairs = asyncio.get_event_loop().run_until_complete(collect())
    rules = to_rewrites(pairs)
    body = json.dumps(rules, ensure_ascii=False, indent=2)
    # slug -> domains[] マップ（middleware / artifact-paths の静的解決用）。
    slug_map: dict[str, list[str]] = {}
    for host, slug in pairs:
        slug_map.setdefault(slug, []).append(host)
    slug_body = json.dumps(slug_map, ensure_ascii=False, indent=2)

    OUT.write_text(
        "// AUTO-GENERATED by scripts/generate_custom_domain_rewrites.py — do not edit.\n"
        "// 接続済み独自ドメインの host条件付き rewrite ＋ slug→domains マップ。\n"
        "// 新しい独自ドメインを接続したら本スクリプトを再実行して再デプロイすること。\n"
        "type HostRewrite = {\n"
        "  source: string;\n"
        "  has: { type: 'host'; value: string }[];\n"
        "  destination: string;\n"
        "};\n\n"
        "export const CUSTOM_DOMAIN_REWRITES: HostRewrite[] = "
        + body
        + ";\n\n"
        "// 独自ドメインの host 解決を静的にする（middleware の動的fetch依存を補強し、\n"
        "// /artifacts/<slug> 直アクセスが /login に落ちる事故を防ぐ）。\n"
        "export const CUSTOM_DOMAIN_SLUG_MAP: Record<string, string[]> = "
        + slug_body
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(pairs)} domains, {len(rules)} rules)")
    for host, slug in pairs:
        print(f"  {host} -> {slug}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
