'use client';
import { useEffect, useRef, useState } from 'react';
import { Mic, Square, Upload, Plus, FileText, ArrowRight, RefreshCw, LockKeyhole, Send } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { EditableText } from '@/components/dan/editable';
import { useSetupGate } from '@/hooks/use-setup-gate';
import { api } from '@/lib/api-client';
import { articleOf, editorialRequest, publishRequest, emptyArticle, ROOM_ID, type Row, type Article } from './model';
import { call, findWorkspace, saveArticle, uploadAudio } from './api';
import styles from './style.module.css';
import { RecordedAudio } from './recorded-audio';

export function PageBody() {
 const [root,setRoot]=useState<Row>();const [rows,setRows]=useState<Row[]>([]);const [selected,setSelected]=useState<Row>();
 const [draft,setDraft]=useState<Article>(emptyArticle);const [tab,setTab]=useState('つくる');const [busy,setBusy]=useState(false);
 const [dirty,setDirty]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const [recording,setRecording]=useState(false);const [confirm,setConfirm]=useState<'publish'|'delete'|null>(null);
 const [preview,setPreview]=useState(true);const [loading,setLoading]=useState(true);const recorder=useRef<MediaRecorder|null>(null);
 const fileInput=useRef<HTMLInputElement>(null);const [audioBlob,setAudioBlob]=useState<Blob>();
 const [inputs,setInputs]=useState<MediaDeviceInfo[]>([]);
 const [inputId,setInputId]=useState('');const [activeInput,setActiveInput]=useState('');
 async function scanInputs(){const list=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='audioinput'&&d.deviceId);setInputs(list);return list;}
 function chooseInput(id:string){setInputId(id);try{localStorage.setItem('voice-note-microphone',id);}catch{}}
 useEffect(()=>{try{setInputId(localStorage.getItem('voice-note-microphone')||'');}catch{}const refreshInputs=()=>{void scanInputs().catch(()=>{});};refreshInputs();navigator.mediaDevices?.addEventListener('devicechange',refreshInputs);return()=>navigator.mediaDevices?.removeEventListener('devicechange',refreshInputs);},[]);
 async function identifyInputs(){await run(async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());const list=await scanInputs();if(!inputId){const preferred=list.find(d=>/^In 1-2.*MOTU M Series/i.test(d.label));if(preferred)chooseInput(preferred.deviceId);}});}
 const gate=useSetupGate(async()=>Boolean(await findWorkspace()));
 async function refresh(selectId?:string){setLoading(true);setError('');try{const w=await findWorkspace();if(!w)throw new Error('本人アカウントで編集室を開いてください。');setRoot(w);const list=await call<Row[]>('/dan-notion/blocks/'+w.id+'/children');setRows(list);if(selectId){const r=list.find(x=>x.id===selectId);if(r){setSelected(r);setDraft(articleOf(r));setDirty(false);}}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();return()=>{recorder.current?.stream.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty||audioBlob){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,audioBlob]);
 const update=(patch:Partial<Article>)=>{setDraft(v=>({...v,...patch}));setDirty(true);};
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!selected)throw new Error('記事を作成してください。');const r=await saveArticle(selected,draft);setSelected(r);setRows(v=>v.map(x=>x.id===r.id?r:x));setDirty(false);return r;}
 async function create(){await run(async()=>{if(!root)throw new Error('保存先に接続してください。');if(selected&&dirty)await save();const a=emptyArticle();const r=await call<Row>('/dan-notion/blocks','POST',{type:'page',parent_id:root.id,properties:{title:a.title,kind:'voice_note_article',article:a},content:[]});setRows(v=>[...v,r]);setSelected(r);setDraft(a);setDirty(false);setTab('つくる');});}
 async function pick(row:Row){await run(async()=>{if(recording||audioBlob)throw new Error('録音を保存してから記事を切り替えてください。');if(selected&&dirty)await save();setSelected(row);setDraft(articleOf(row));setDirty(false);setTab('つくる');});}
 async function attach(file:File){await run(async()=>{if(!selected)throw new Error('記事を作成してください。');const audio=await uploadAudio(file);const a={...draft,audio:[...draft.audio,audio]};const r=await saveArticle(selected,a);setSelected(r);setRows(v=>v.map(x=>x.id===r.id?r:x));setDraft(a);setDirty(false);setAudioBlob(undefined);setMessage('音声を保存しました。「記事に整える」で制作を始めます。');});}
 async function record(){if(recording){recorder.current?.stop();setRecording(false);return;}await run(async()=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error('この画面では録音できません。音声ファイルを追加してください。');const policy=(document as Document & {featurePolicy?:{allowsFeature:(name:string)=>boolean}}).featurePolicy;
 if(policy && !policy.allowsFeature('microphone'))throw new Error('編集室の表示枠でマイクが許可されていません。チャット画面を再読み込みしてから、もう一度録音してください。');
 let stream:MediaStream|undefined;
 setMessage('ブラウザにマイクの許可が表示されたら「許可」を押してください。');
 try{stream=await navigator.mediaDevices.getUserMedia({audio:inputId?{deviceId:{exact:inputId}}:true});
 const list=await scanInputs();
 if(!inputId){const preferred=list.find(d=>/^In 1-2.*MOTU M Series/i.test(d.label));if(preferred){if(stream.getAudioTracks()[0]?.getSettings().deviceId!==preferred.deviceId){stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:{exact:preferred.deviceId}}});}chooseInput(preferred.deviceId);}}
 setActiveInput(stream.getAudioTracks()[0]?.label||'端末の標準マイク');setMessage('');}catch(e){
 stream?.getTracks().forEach(t=>t.stop());setMessage('');
 const name=(e as DOMException).name;
 if(name==='NotAllowedError'||name==='PermissionDeniedError')throw new Error('マイクの使用が許可されていません。ブラウザのアドレス欄左側にあるサイト設定でマイクを許可し、ページを再読み込みしてください。');
 if(name==='OverconstrainedError')throw new Error('選んだマイクが見つかりません。接続を確認し、録音に使う入力を選び直してください。');
 if(name==='NotFoundError')throw new Error('マイクが見つかりません。マイクを接続してから、もう一度録音してください。');
 if(name==='NotReadableError')throw new Error('マイクを開始できません。ほかのアプリのマイク使用や、端末のマイク設定を確認してください。');
 throw new Error('録音を開始できませんでした。ページを再読み込みして、もう一度お試しください。');
 }
 if(!stream)throw new Error('マイクを開始できませんでした。');const recordingStream=stream;
 try{const r=new MediaRecorder(recordingStream);recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{setAudioBlob(new Blob(chunks,{type:r.mimeType}));recordingStream.getTracks().forEach(t=>t.stop());};r.onerror=()=>{recordingStream.getTracks().forEach(t=>t.stop());setRecording(false);setError('録音が中断しました。');};r.start(1000);setRecording(true);}catch(e){stream.getTracks().forEach(t=>t.stop());throw e;}});}
 async function send(kind:'edit'|'publish'){await run(async()=>{if(kind==='edit'&&!draft.transcript.trim()&&!draft.audio.length)throw new Error('音声か話した内容を追加してください。');if(kind==='publish'&&(!draft.title.trim()||!draft.free.trim()||(draft.price>0&&!draft.paid.trim())||draft.questions.length))throw new Error('本文と確認事項を解消してから投稿してください。');const row=await save();setConfirm(null);setMessage('ダンがこのチャットで対応しています。');await api.sm.sendMessageStream({message:kind==='edit'?editorialRequest(row.id):publishRequest(row.id),session_id:ROOM_ID,client_message_id:crypto.randomUUID()},{onError:e=>setError(e),onComplete:()=>{void refresh(row.id);},onAIMessage:m=>setMessage(m.content),onInterrupted:()=>setMessage('接続が切れました。このチャットの処理状況を確認してから更新してください。')});});}
 const month=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}).slice(0,7);
 const measured=rows.map(articleOf).filter(a=>a.salesMonth===month&&a.checkedAt);const basis=root?.properties.target_basis==='gross'?'gross':'received';const amount=measured.reduce((n,a)=>n+a[basis],0);const target=Number(root?.properties.monthly_target)||300000;
 return <main className={styles.app}>
 <header className={styles.header}><div className={styles.brand}><FileText size={23}/><EditableText as="span" editId="voice-note-home-brand">話して、noteに。</EditableText></div><EditableText as="span" editId="voice-note-home-private" className={styles.private}><LockKeyhole size={14}/>自分だけの編集室</EditableText></header>
 <div className={styles.top}><div><EditableText as="p" editId="voice-note-home-eyebrow" className={styles.eyebrow}>あなたの経験を、誰かの役に立つ記事へ。</EditableText><EditableText as="h1" editId="voice-note-home-heading">考えは、話すところから。</EditableText><EditableText as="p" editId="voice-note-home-lead" className={styles.lead}>まとまっていなくて大丈夫。話した内容を残して、ダンと記事に仕上げます。</EditableText></div><div className={styles.goal}><EditableText as="small" editId="voice-note-home-goal-label">今月の{basis==='gross'?'売上':'受取額'} / 目標</EditableText><EditableText as="strong" editId="voice-note-home-goal-value">{measured.length?'¥'+amount.toLocaleString():'未集計'} <span>/ ¥{target.toLocaleString()}</span></EditableText><progress max={target} value={amount}/><EditableText as="small" editId="voice-note-home-goal-help">{measured.length?'確認済みの実績を集計':'売上を確認したら「実績」に記録'}</EditableText></div></div>
 <nav className={styles.tabs} aria-label="編集室のメニュー">{['つくる','記事一覧','実績'].map(t=><EditableText as="button" editId={`voice-note-home-tab-${t}`} key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</EditableText>)}<EditableText as="button" editId="voice-note-home-refresh" className={styles.refresh} disabled={busy||dirty||recording||Boolean(audioBlob)} onClick={()=>void refresh(selected?.id)}><RefreshCw size={15}/>更新</EditableText></nav>
 <div aria-live="polite">{error&&<p role="alert" data-edit-id="voice-note-home-error" className={styles.error}>{error}</p>}{message&&<p data-edit-id="voice-note-home-result" className={styles.notice}>{message}</p>}</div>
 {loading?<div className={styles.empty}>編集室を読み込んでいます…</div>:!root?<div className={styles.empty}><EditableText as="h2" editId="voice-note-home-auth-title">ダンの本人アカウントで開く編集室です。</EditableText><EditableText as="p" editId="voice-note-home-auth-copy">公開ページに記事本文は表示されません。</EditableText><EditableText as="button" editId="voice-note-home-retry" onClick={()=>void refresh()}>接続を再確認</EditableText></div>:<>
 {tab==='つくる'&&<div className={styles.workspace}><aside className={styles.side}><button className={styles.primary} disabled={busy||recording||Boolean(audioBlob)} onClick={()=>void create()}><Plus size={17}/>新しい記事</button><small>記事の素材と下書き</small>{rows.map(r=><button className={selected?.id===r.id?styles.chosen:styles.item} key={r.id} onClick={()=>void pick(r)} disabled={busy}><span>{articleOf(r).title}</span><small>{articleOf(r).status}</small></button>)}<div className={styles.hint}><strong>こんな話から</strong><p>最近、面倒だったこと。<br/>試して失敗したこと。<br/>前より楽になった工夫。</p></div></aside>
 {!selected?<section className={styles.start}><div className={styles.mic}><Mic size={34}/></div><EditableText as="h2" editId="voice-note-home-start">いつもの話が、記事の種になる。</EditableText><EditableText as="p" editId="voice-note-home-start-copy">音声を録る。ファイルを追加する。<br/>このチャットで話す。どこからでも始められます。</EditableText><EditableText as="button" editId="voice-note-home-first-article" className={styles.primary} onClick={()=>void create()} disabled={busy}>最初の記事をつくる<ArrowRight size={17}/></EditableText><div className={styles.flow}><span>01 話す</span><span>02 記事に整える</span><span>03 確認して投稿</span></div></section>:<fieldset className={styles.editor} disabled={busy}>
 <div className={styles.editorTop}><span>{draft.status}</span><span>{dirty?'未保存の変更があります':'保存済み'}</span><button disabled={busy||!dirty} onClick={()=>void run(async()=>{await save();setMessage('保存しました。');})}>保存</button></div>
 <label className={styles.field}>タイトル<input value={draft.title} onChange={e=>update({title:e.target.value})}/></label>
 <details open={!draft.free}><summary>話したこと・音声</summary><label className={styles.field}>録音に使う入力<select value={inputId} disabled={busy||recording} onChange={e=>chooseInput(e.target.value)}><option value="">自動選択（MOTUの入力を優先）</option>{inputId&&!inputs.some(d=>d.deviceId===inputId)&&<option value={inputId}>保存した入力（接続を確認してください）</option>}{inputs.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'マイク'}</option>)}</select></label><button disabled={busy||recording} onClick={()=>void identifyInputs()}>入力機器を確認</button><p>ShureをMOTUにつないでいる場合は「In 1-2 (MOTU M Series)」を選びます。LoopbackはPC内の音を取り込む入力です。</p>{recording&&<p role="status">録音中の入力：{activeInput}</p>}<div className={styles.actions}><button onClick={()=>void record()} disabled={busy||Boolean(audioBlob)}>{recording?<Square size={16}/>:<Mic size={16}/>} {recording?'録音を止める':'録音する'}</button><button disabled={busy||recording} onClick={()=>fileInput.current?.click()}><Upload size={16}/>音声を追加</button><input ref={fileInput} type="file" accept="audio/*,.webm,.mp4" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void attach(f);e.target.value='';}}/></div>
 {audioBlob&&<div className={styles.audio}><RecordedAudio blob={audioBlob}/><button disabled={busy} onClick={()=>void attach(new File([audioBlob],'録音.'+(audioBlob.type.includes('mp4')?'m4a':'webm'),{type:audioBlob.type}))}>この録音を保存</button><button disabled={busy} onClick={()=>setAudioBlob(undefined)}>取り直す</button></div>}
 {draft.audio.map(a=><div key={a.url} className={styles.audio}><small>{a.name}</small>{a.url?.trim()?<audio controls src={a.url}/>:<span>音声の保存先が見つかりません。</span>}</div>)}
 <label className={styles.field}>話した内容<textarea rows={5} value={draft.transcript} placeholder="思いついた順で、そのまま。音声だけでも記事にできます。" onChange={e=>update({transcript:e.target.value})}/></label><button className={styles.primary} disabled={busy||recording||Boolean(audioBlob)||(!draft.transcript.trim()&&!draft.audio.length)} onClick={()=>void send('edit')}>記事に整える<ArrowRight size={16}/></button></details>
 {draft.questions.length>0&&<div className={styles.notice}><strong>記事を仕上げるための確認</strong>{draft.questions.map(q=><p key={q}>{q}</p>)}</div>}
 <div className={styles.editorTop}><h2>記事の仕上がり</h2><button onClick={()=>setPreview(!preview)}>{preview?'本文を編集':'読みやすさを確認'}</button></div>
 {preview?<div className={styles.paper}>{draft.free?<ReactMarkdown>{draft.free}</ReactMarkdown>:<p className={styles.placeholder}>記事ができると、ここで見出しや太字を含めて確認できます。</p>}{draft.price>0&&<div className={styles.payline}><LockKeyhole size={15}/>ここから有料 · ¥{draft.price.toLocaleString()}</div>}{draft.paid&&<ReactMarkdown>{draft.paid}</ReactMarkdown>}</div>:<><label className={styles.field}>無料で読める部分<textarea rows={10} value={draft.free} onChange={e=>update({free:e.target.value,status:'編集中'})}/></label><div className={styles.payline}>この下から有料部分</div><label className={styles.field}>購入した人が読める部分<textarea rows={10} value={draft.paid} onChange={e=>update({paid:e.target.value,status:'編集中'})}/></label><small>見出しは ##、強調は **太字** で囲みます。</small></>}
 <div className={styles.settings}><label className={styles.field}>販売価格（円・0で無料）<input type="number" min="0" step="1" value={draft.price} onChange={e=>update({price:Number(e.target.value)})}/></label><label className={styles.field}>公開希望日時（日本時間・空欄で今すぐ）<input type="datetime-local" value={draft.scheduledAt} onChange={e=>update({scheduledAt:e.target.value})}/></label></div>
 <div className={styles.footer}><button onClick={()=>setConfirm('delete')} disabled={busy||recording}>削除</button><button className={styles.primary} disabled={busy||recording||Boolean(audioBlob)||!draft.free.trim()||draft.questions.length>0} onClick={()=>setConfirm('publish')}><Send size={16}/>投稿内容を確認</button></div></fieldset>}</div>}
 {tab==='記事一覧'&&<section className={styles.list}><h2>すべての記事 <small>{rows.length}本</small></h2>{!rows.length?<p>まだ記事はありません。「つくる」から音声を追加できます。</p>:rows.map(r=>{const a=articleOf(r);return <button key={r.id} className={styles.listRow} onClick={()=>void pick(r)}><FileText size={20}/><span><strong>{a.title}</strong><small>{a.status} · {a.price?'¥'+a.price.toLocaleString():'無料'}{a.scheduledAt?' · 公開希望 '+a.scheduledAt.replace('T',' '):''}</small></span><ArrowRight size={17}/></button>;})}</section>}
 {tab==='実績'&&<section className={styles.list}><h2>月30万円までの記録</h2><p className={styles.lead}>noteで確認した数字を保存します。未入力の実績を売上ゼロとは扱いません。</p><div className={styles.settings}><label className={styles.field}>目標の基準<select value={basis} disabled={busy} onChange={e=>void run(async()=>{const r=await call<Row>('/dan-notion/blocks/'+root.id,'PATCH',{properties:{...root.properties,target_basis:e.target.value}});setRoot(r);})}><option value="received">手数料を引いた受取額</option><option value="gross">手数料を引く前の売上</option></select></label><div className={styles.calculation}><strong>¥1,000 × 300件 = 売上 ¥300,000</strong><small>価格の例です。受取額は決済方法などで変わります。</small></div></div>
 {selected?<><h3>{draft.title}</h3><div className={styles.settings}><label className={styles.field}>集計月<input type="month" value={draft.salesMonth} onChange={e=>update({salesMonth:e.target.value,checkedAt:'',purchases:0,gross:0,received:0})}/></label>{(['purchases','gross','received'] as const).map((key,i)=><label key={key} className={styles.field}>{['購入件数','売上（円）','受取額（円）'][i]}<input type="number" min="0" value={draft[key]} onChange={e=>update({[key]:Number(e.target.value)})}/></label>)}</div><label className={styles.field}>公開記事URL<input type="url" value={draft.noteUrl} onChange={e=>update({noteUrl:e.target.value})}/></label><button className={styles.primary} disabled={busy} onClick={()=>void run(async()=>{const a={...draft,checkedAt:new Date().toISOString()};const r=await saveArticle(selected,a);setDraft(a);setSelected(r);setRows(v=>v.map(x=>x.id===r.id?r:x));setDirty(false);setMessage('実績を保存しました。');})}>確認した実績を保存</button></>:<p>「記事一覧」で記事を選ぶと、実績を入力できます。</p>}</section>}
 </>}
 {confirm&&<div className={styles.backdrop}><div role="dialog" aria-modal="true" aria-labelledby="confirm-title" className={styles.dialog}><h2 id="confirm-title">{confirm==='delete'?'この記事を削除しますか？':'この内容をnoteに投稿します'}</h2><p>{draft.title}</p>{confirm==='publish'&&<><p>{draft.price?'有料 ¥'+draft.price.toLocaleString():'無料'} · {draft.scheduledAt?draft.scheduledAt.replace('T',' ')+'（日本時間）':'今すぐ公開'}</p><p>本文・価格・有料ラインを確認したうえで、ダンに投稿を依頼します。</p></>}<div className={styles.actions}><button onClick={()=>setConfirm(null)}>戻る</button><button className={styles.primary} disabled={busy} onClick={()=>{if(confirm==='publish'){void send('publish');}else{void run(async()=>{await call('/dan-notion/blocks/'+selected!.id,'DELETE');setRows(v=>v.filter(x=>x.id!==selected!.id));setSelected(undefined);setDraft(emptyArticle());setDirty(false);setConfirm(null);});}}}>{confirm==='delete'?'削除する':'この内容で投稿を依頼'}</button></div></div></div>}
 <span hidden>{gate.status}</span></main>;
}
