// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.
// 成果物ごとの公開ページ一覧（独自ドメイン公開時の sitemap 生成に使用）。
export const ARTIFACT_PAGES: Record<string, string[]> = {
  "aix-dashboard": [
    "/"
  ],
  "arm-roll": [
    "/"
  ],
  "bookings": [
    "/"
  ],
  "denki-knowledge": [
    "/"
  ],
  "inspection-report": [
    "/"
  ],
  "kittoku": [
    "/",
    "/careers",
    "/company",
    "/contact",
    "/services",
    "/v2"
  ],
  "new-attack": [
    "/"
  ],
  "paina": [
    "/",
    "/business",
    "/contact"
  ],
  "publish": [
    "/"
  ],
  "salonboard-monitor": [
    "/"
  ],
  "salonboard-styleup": [
    "/"
  ],
  "test-edit": [
    "/"
  ],
  "yonago-gojo": [
    "/"
  ],
  "yonago-gojo-comp": [
    "/"
  ],
  "yonago-gojo-v1": [
    "/"
  ]
};
