// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.
// 自前の sitemap.ts を持つ成果物の読み込み口。app/sitemap.ts が ARTIFACT_PAGES より優先して使う。
import type { MetadataRoute } from "next";

type SitemapModule = {
  default: () => MetadataRoute.Sitemap | Promise<MetadataRoute.Sitemap>;
};

export const ARTIFACT_SITEMAPS: Record<string, () => Promise<SitemapModule>> = {
  "denki-knowledge": () => import("@/app/artifacts/denki-knowledge/sitemap"),
};
