// AUTO-GENERATED by scripts/generate_sitemap_registry.py — do not edit.
// 成果物ごとの公開ページ一覧（独自ドメイン公開時の sitemap 生成に使用）。
export const ARTIFACT_PAGES: Record<string, string[]> = {
  "aix-dashboard": [
    "/"
  ],
  "arm-roll": [
    "/"
  ],
  "bookings": [
    "/"
  ],
  "denki-knowledge": [
    "/",
    "/guides/dokuritsu",
    "/guides/haikyu-jiko",
    "/guides/nenji-tenken",
    "/qa"
  ],
  "editable-lp-lab": [
    "/"
  ],
  "floor-lp-compare": [
    "/"
  ],
  "floor-lp-native": [
    "/"
  ],
  "himawari-seitai": [
    "/"
  ],
  "inspection-report": [
    "/"
  ],
  "itsuki-lab": [
    "/"
  ],
  "itsuki-line": [
    "/"
  ],
  "kittoku": [
    "/",
    "/careers",
    "/company",
    "/contact",
    "/services",
    "/v2"
  ],
  "moonbox-jp": [
    "/"
  ],
  "moonbox-proposal": [
    "/"
  ],
  "new-attack": [
    "/"
  ],
  "oku-yukadanbou": [
    "/"
  ],
  "oku-yukadanbou-real": [
    "/",
    "/email",
    "/survey"
  ],
  "paina": [
    "/",
    "/business",
    "/contact"
  ],
  "pornblocker-guard-beacon": [
    "/",
    "/thanks"
  ],
  "pornblocker-roadmap": [
    "/"
  ],
  "publish": [
    "/"
  ],
  "safeguard": [
    "/",
    "/download",
    "/legal",
    "/privacy",
    "/terms"
  ],
  "safeguard-layers": [
    "/",
    "/download",
    "/legal",
    "/privacy",
    "/terms"
  ],
  "salonboard-monitor": [
    "/"
  ],
  "salonboard-styleup": [
    "/",
    "/privacy",
    "/terms"
  ],
  "styleup-lp": [
    "/"
  ],
  "test-edit": [
    "/"
  ],
  "voice-note": [
    "/"
  ],
  "voice-playground": [
    "/"
  ],
  "yonago-gojo": [
    "/"
  ],
  "yonago-gojo-comp": [
    "/"
  ],
  "yonago-gojo-v1": [
    "/"
  ]
};
