// AUTO-GENERATED by scripts/generate_custom_domain_rewrites.py — do not edit.
// 接続済み独自ドメインの host条件付き rewrite ＋ slug→domains マップ。
// 新しい独自ドメインを接続したら本スクリプトを再実行して再デプロイすること。
type HostRewrite = {
  source: string;
  has: { type: 'host'; value: string }[];
  destination: string;
};

export const CUSTOM_DOMAIN_REWRITES: HostRewrite[] = [
  {
    "source": "/",
    "has": [
      {
        "type": "host",
        "value": "paina.info"
      }
    ],
    "destination": "/artifacts/paina"
  },
  {
    "source": "/:path+",
    "has": [
      {
        "type": "host",
        "value": "paina.info"
      }
    ],
    "destination": "/artifacts/paina/:path+"
  },
  {
    "source": "/",
    "has": [
      {
        "type": "host",
        "value": "www.paina.info"
      }
    ],
    "destination": "/artifacts/paina"
  },
  {
    "source": "/:path+",
    "has": [
      {
        "type": "host",
        "value": "www.paina.info"
      }
    ],
    "destination": "/artifacts/paina/:path+"
  }
];

// 独自ドメインの host 解決を静的にする（middleware の動的fetch依存を補強し、
// /artifacts/<slug> 直アクセスが /login に落ちる事故を防ぐ）。
export const CUSTOM_DOMAIN_SLUG_MAP: Record<string, string[]> = {
  "paina": [
    "paina.info",
    "www.paina.info"
  ]
};
